"""initial schema

Revision ID: 4bcb1229f7af
Revises: 
Create Date: 2026-07-15 21:59:12.507576
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4bcb1229f7af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('contractor_type', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('default_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractors')),
    sa.UniqueConstraint('tenant_id', 'contractor_type', 'normalized_name', name='uq_contractors_identity')
    )
    op.create_index(op.f('ix_contractors_tenant_id'), 'contractors', ['tenant_id'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('default_basis', sa.String(length=30), nullable=False),
    sa.Column('default_discount', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_sources_tenant_name')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('contractor_rates',
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('commission_per_order', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_contractor_rates_contractor_id_contractors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contractor_rates')),
    sa.UniqueConstraint('tenant_id', 'contractor_id', 'effective_date', name='uq_contractor_rates_effective')
    )
    op.create_index(op.f('ix_contractor_rates_contractor_id'), 'contractor_rates', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contractor_rates_effective_date'), 'contractor_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_contractor_rates_tenant_id'), 'contractor_rates', ['tenant_id'], unique=False)
    op.create_table('export_logs',
    sa.Column('export_format', sa.String(length=10), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_export_logs_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_logs'))
    )
    op.create_index(op.f('ix_export_logs_tenant_id'), 'export_logs', ['tenant_id'], unique=False)
    op.create_table('export_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_export_templates_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_templates'))
    )
    op.create_index(op.f('ix_export_templates_tenant_id'), 'export_templates', ['tenant_id'], unique=False)
    op.create_table('members',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_members_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_members_tenant_user')
    )
    op.create_index(op.f('ix_members_tenant_id'), 'members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_no', sa.String(length=40), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('contractor_type', sa.String(length=20), nullable=False),
    sa.Column('contractor_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('order_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('coupon_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_paid', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_basis_snapshot', sa.String(length=30), nullable=False),
    sa.Column('discount_snapshot', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('settlement_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_overridden', sa.Boolean(), nullable=False),
    sa.Column('income_override_reason', sa.String(length=300), nullable=True),
    sa.Column('commission', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_overridden', sa.Boolean(), nullable=False),
    sa.Column('commission_override_reason', sa.String(length=300), nullable=True),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_orders_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_orders_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('tenant_id', 'order_no', name='uq_orders_tenant_no')
    )
    op.create_index(op.f('ix_orders_business_date'), 'orders', ['business_date'], unique=False)
    op.create_index(op.f('ix_orders_contractor_id'), 'orders', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_orders_contractor_type'), 'orders', ['contractor_type'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=False)
    op.create_index(op.f('ix_orders_source_id'), 'orders', ['source_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refresh_sessions_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_sessions_token_hash'))
    )
    op.create_index(op.f('ix_refresh_sessions_tenant_id'), 'refresh_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('settlements',
    sa.Column('settlement_no', sa.String(length=40), nullable=False),
    sa.Column('settlement_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('counterparty_name_snapshot', sa.String(length=100), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('order_amount_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_paid_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_income_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('account_balance_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversal_reason', sa.String(length=300), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_settlements_confirmed_by_users')),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_settlements_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_settlements_created_by_users')),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], name=op.f('fk_settlements_reversed_by_users')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_settlements_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlements')),
    sa.UniqueConstraint('tenant_id', 'settlement_no', name='uq_settlements_tenant_no')
    )
    op.create_index(op.f('ix_settlements_contractor_id'), 'settlements', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_no'), 'settlements', ['settlement_no'], unique=False)
    op.create_index(op.f('ix_settlements_settlement_type'), 'settlements', ['settlement_type'], unique=False)
    op.create_index(op.f('ix_settlements_source_id'), 'settlements', ['source_id'], unique=False)
    op.create_index(op.f('ix_settlements_status'), 'settlements', ['status'], unique=False)
    op.create_index(op.f('ix_settlements_tenant_id'), 'settlements', ['tenant_id'], unique=False)
    op.create_table('source_rates',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('settlement_basis', sa.String(length=30), nullable=False),
    sa.Column('discount', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_rates_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_rates')),
    sa.UniqueConstraint('tenant_id', 'source_id', 'effective_date', name='uq_source_rates_effective')
    )
    op.create_index(op.f('ix_source_rates_effective_date'), 'source_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_source_rates_source_id'), 'source_rates', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_rates_tenant_id'), 'source_rates', ['tenant_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('account', sa.String(length=30), nullable=False),
    sa.Column('entry_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('reversed_entry_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name=op.f('fk_ledger_entries_contractor_id_contractors')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ledger_entries_created_by_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_ledger_entries_order_id_orders')),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['ledger_entries.id'], name=op.f('fk_ledger_entries_reversed_entry_id_ledger_entries')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ledger_entries_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_account'), 'ledger_entries', ['account'], unique=False)
    op.create_index(op.f('ix_ledger_entries_business_date'), 'ledger_entries', ['business_date'], unique=False)
    op.create_index(op.f('ix_ledger_entries_contractor_id'), 'ledger_entries', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_order_id'), 'ledger_entries', ['order_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_source_id'), 'ledger_entries', ['source_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_tenant_id'), 'ledger_entries', ['tenant_id'], unique=False)
    op.create_table('settlement_items',
    sa.Column('settlement_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_settlement_items_order_id_orders')),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], name=op.f('fk_settlement_items_settlement_id_settlements')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_items')),
    sa.UniqueConstraint('settlement_id', 'order_id', name='uq_settlement_items_order')
    )
    op.create_index(op.f('ix_settlement_items_order_id'), 'settlement_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_settlement_items_settlement_id'), 'settlement_items', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_items_tenant_id'), 'settlement_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settlement_items_tenant_id'), table_name='settlement_items')
    op.drop_index(op.f('ix_settlement_items_settlement_id'), table_name='settlement_items')
    op.drop_index(op.f('ix_settlement_items_order_id'), table_name='settlement_items')
    op.drop_table('settlement_items')
    op.drop_index(op.f('ix_ledger_entries_tenant_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_source_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_order_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_contractor_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_business_date'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_source_rates_tenant_id'), table_name='source_rates')
    op.drop_index(op.f('ix_source_rates_source_id'), table_name='source_rates')
    op.drop_index(op.f('ix_source_rates_effective_date'), table_name='source_rates')
    op.drop_table('source_rates')
    op.drop_index(op.f('ix_settlements_tenant_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_status'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_source_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_type'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_settlement_no'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_contractor_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_tenant_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_source_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_contractor_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_contractor_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_business_date'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_tenant_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_export_templates_tenant_id'), table_name='export_templates')
    op.drop_table('export_templates')
    op.drop_index(op.f('ix_export_logs_tenant_id'), table_name='export_logs')
    op.drop_table('export_logs')
    op.drop_index(op.f('ix_contractor_rates_tenant_id'), table_name='contractor_rates')
    op.drop_index(op.f('ix_contractor_rates_effective_date'), table_name='contractor_rates')
    op.drop_index(op.f('ix_contractor_rates_contractor_id'), table_name='contractor_rates')
    op.drop_table('contractor_rates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_contractors_tenant_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###